version: "3.8"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - .:/var/app/royhome-api
    ports:
      - "5000:5000"
    links:
      - local-db
    depends_on:
      - flyway

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://local-db:5432/royHome -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./src:/flyway/sql
    links:
      - local-db

  local-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=royHome
