server:
  tomcat:
    accesslog:
      enabled: off
  ssl:
    key-store-password: ${ROYHOME_SSL_PASSWORD}
    key-store: /var/cert/royhome/cert.jks
    key-store-type: PKCS12
    enabled: true
  port: 5000

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://local-db:5432/royHome
