server:
  tomcat:
    accesslog:
      enabled: off
  ssl:
    key-store: C:\Users\kroy7\royhome\cert\cert.jks
  port: 5000

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/royHome
