server:
  tomcat:
    accesslog:
      enabled: off
  ssl:
    enabled: false
  port: 5000

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/royHome
